######################################################################
# Automatically generated by qmake (1.07a) Tue Apr 20 09:16:46 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += CombineRequest.h
SOURCES += CombineRequest.cc main.cc
