######################################################################
# Automatically generated by qmake (1.07a) Fri Apr 9 15:46:00 2010
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cc
