######################################################################
# Automatically generated by qmake (1.07a) Thu Mar 18 10:30:30 2010
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cc
