######################################################################
# Automatically generated by qmake (1.07a) Thu Apr 8 14:06:33 2010
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cc
