######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 11 14:18:17 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cc
